### ISSUE TITLE
Unable To Like And Comment On Stories

### ISSUE THREAD

**Issue by shine-jayakumar** [shine-jayakumar/insta-likecom-bot#104]
Tests failed - Like, Comment on stories

**Comment by synopsis8** [comment]
Before even like and comment on stories, I would like first to pause them.
And this is where I encounter issues.

In "insta.py" function "pause_story"
I have replaced the line
`wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '._ac0m'))).find_element(By.CSS_SELECTOR, 'svg[aria-label="Pause"]').click()`
to
`wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '._ac0m'))).find_element(By.CSS_SELECTOR, 'svg[aria-label*="Pause"]').click()`
or
`wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '._ac0m'))).find_element(By.CSS_SELECTOR, 'svg[aria-label*="Pause"]').click()`

In order to match several languages for the webdriver : no success, I'm ending up in error `*] => [pause_story] Error: TimeoutException`

Then I have tried the selection using the XPATH instead
`wait.until(EC.presence_of_element_located((By.XPATH, '//button[@class="x1lliihq x1n2onr6 xq3z1fi"]'))).click()
`
There I'm not lucky either
