### ISSUE TITLE
 What could cause this error?

### ISSUE THREAD

**Issue by knmzz** [shine-jayakumar/insta-likecom-bot#9]
![image](https://user-images.githubusercontent.com/97535534/182939713-7c50f867-25cf-48b8-92bf-992d6812dfc7.png))

![image](https://user-images.githubusercontent.com/97535534/182941131-c91bd86e-d6f5-4c00-8498-f8aab5d80578.png)

All transactions are getting this error.

**Comment by shine-jayakumar** [comment]
This error happened because the script was unable to get the number of posts on the page. This may happen if the section containing the number of posts was not loaded in time. 
I have added logic to reattempt capturing the number of posts for the page:

Log from recent run:
[*] => Script started
[*] => Loaded comments from testcomments.txt
[*] => Downloading webdriver for your version of Chrome
[*] => Initializing instagram user
[*] => Setting target to: opensea
[*] => Attempting to log in with shinej08
[*] => Login successful
[*] => Skipping Save Login Info
[*] => Do not save login info: True
[*] => Opening target opensea
[open_target]: Attempt - 1
[get_number_of_posts]: Attempt - 1
[*] => No. of posts found: 683
[*] => Checking if comments are disabled
[*] => Comments are enabled
[*] => Number of posts to like: 2
[*] => Liking post: 1
[like]: Attempt - 1
[*] => Commenting on the post
[comment]: Attempt - 1
[comment]: Attempt - 2
[*] => Commented: Amazing content Follow me _____
[*] => Moving on to the next post
[*] => Waiting for 4 seconds
[*] => Liking post: 2
[like]: Attempt - 1
[*] => Commenting on the post
[comment]: Attempt - 1
[comment]: Attempt - 2
[*] => Commented: Amazing content Follow me ______
[*] => Moving on to the next post
[*] => Waiting for 9 seconds
[*] => Script finished successfully
[*] => Total time taken: 68.0698 seconds

**Comment by knmzz** [comment]
[*] => Script started
[*] => Downloading webdriver for your version of Chrome
[*] => Initializing instagram user
[*] => Setting target to: nftstarnetwork
[*] => Attempting to log in with adesing007
[*] => Login successful
[*] => Skipping Save Login Info
[*] => Do not save login info: True
[*] => Opening target nftstarnetwork
[open_target]: Attempt - 1
[*] => Unable to find posts. Reloading the target
[open_target]: Attempt - 1
[*] => Unable to find posts. Reloading the target
[open_target]: Attempt - 1
[*] => Unable to find posts. Reloading the target
[open_target]: Attempt - 1
[*] => Script ended with error : No posts found for the target

**Comment by shine-jayakumar** [comment]
> 
1) Which version of Chrome are you using?
2) Are you running it on Windows, Mac, or Linux?
3) Have you tried a different username?

This is working for me:
[*] => Script started
[*] => Downloading webdriver for your version of Chrome
[*] => Initializing instagram user
[*] => Setting target to: nftstarnetwork
[*] => Attempting to log in with shinej08
[*] => Login successful
[*] => Skipping Save Login Info
[*] => Do not save login info: True
[*] => Opening target nftstarnetwork
[open_target]: Attempt - 1
[*] => No. of posts found: 12
[*] => Checking if comments are disabled
[*] => Comments are enabled
[*] => Number of posts to like: 2
[*] => Liking post: 1
[like]: Attempt - 1
[*] => Commenting on the post
[comment]: Attempt - 1
[comment]: Attempt - 2
[*] => Commented: The shocker! 😮
[*] => Moving on to the next post
[*] => Waiting for 5 seconds
[*] => Liking post: 2
[like]: Attempt - 1
[*] => Commenting on the post
[comment]: Attempt - 1
[comment]: Attempt - 2
[*] => Commented: The shocker! 😮
[*] => Moving on to the next post
[*] => Waiting for 8 seconds
[*] => Script finished successfully
[*] => Total time taken: 65.7908 seconds

**Comment by knmzz** [comment]
I don't understand why it doesn't work, I tried it on a different user

[*] => Script started
[*] => Downloading webdriver for your version of Chrome
[*] => Initializing instagram user
[*] => Setting target to: elonmusk
[*] => Attempting to log in with adesing007
[*] => Login successful
[*] => Skipping Save Login Info
[*] => Do not save login info: True
[*] => Opening target elonmusk
[open_target]: Attempt - 1
[*] => Unable to find posts. Reloading the target
[open_target]: Attempt - 1
[*] => Unable to find posts. Reloading the target
[open_target]: Attempt - 1

**Comment by shine-jayakumar** [comment]
> I don't understand why it doesn't work, I tried it on a different user
> 
> [_] => Script started [_] => Downloading webdriver for your version of Chrome [_] => Initializing instagram user [_] => Setting target to: elonmusk [_] => Attempting to log in with adesing007 [_] => Login successful [_] => Skipping Save Login Info [_] => Do not save login info: True [_] => Opening target elonmusk [open_target]: Attempt - 1 [_] => Unable to find posts. Reloading the target [open_target]: Attempt - 1 [*] => Unable to find posts. Reloading the target [open_target]: Attempt - 1

I was referring to the username 'adesing007'. Please check if you can login with 'adesing007' and access the page you're trying to automate. Try a different username instead of 'adesing007'.

[*] => Script started
[*] => Downloading webdriver for your version of Chrome
[*] => Initializing instagram user
[*] => Setting target to: elonmusk
[*] => Attempting to log in with shinej08
[*] => Login successful
[*] => Skipping Save Login Info
[*] => Do not save login info: True
[*] => Opening target elonmusk
[open_target]: Attempt - 1
[*] => No. of posts found: 504
[*] => Number of posts to like: 3
[*] => Liking post: 1
[like]: Attempt - 1
[*] => Moving on to the next post
[*] => Waiting for 5 seconds
[*] => Liking post: 2
[like]: Attempt - 1
[*] => Moving on to the next post
[*] => Waiting for 2 seconds
[*] => Liking post: 3
[like]: Attempt - 1
[*] => Moving on to the next post
[*] => Waiting for 10 seconds
[*] => Script finished successfully
[*] => Total time taken: 35.2007 seconds

**Comment by knmzz** [comment]
This is the code I made for the likes

instalikecombot.py nftanimal221  ******  haunted.fork -np 2


[*] => Script started
[*] => Downloading webdriver for your version of Chrome
[*] => Initializing instagram user
[*] => Setting target to: haunted.fork
[*] => Attempting to log in with nftanimal221
[*] => Login successful
[*] => Skipping Save Login Info
[*] => Do not save login info: True
[*] => Opening target haunted.fork
[open_target]: Attempt - 1
[*] => Unable to find posts. Reloading the target
[open_target]: Attempt - 1
[*] => Unable to find posts. Reloading the target
[open_target]: Attempt - 1
[*] => Unable to find posts. Reloading the target
[open_target]: Attempt - 1
[*] => Script ended with error : No posts found for the target
[*] => Total time taken: 130.015 seconds

**Comment by shine-jayakumar** [comment]
> Hello I want to show you with a video, can you tell me if there is any mistake?
> 
>  bandicam.2022-08-10.21-38-51-674.mp4

Amazing! The video helped a lot in figuring out the issue.

The script looks for the word, 'posts', to find the number of posts.
Since you opened the page in a different language than English, script couldn't find the word 'posts'. 

Script has been updated now. 

Also, the script now allows users to create a .env file in the same directory and specify their username, password, and target so they don't have to type it out in the terminal/command prompt. 

There's a sample .env file in the latest push.

**If you still want to provide your username, password, and target through terminal, you can use switch -u username, -p password, and -t target.**

Documentation has been updated.

You can now do a pull again and run the latest script.

Hope that helps. Let me know if it works.

**Comment by knmzz** [comment]
![image](https://user-images.githubusercontent.com/97535534/184222323-195f526f-ccc8-4e84-8471-46a1fab6b1fa.png)

https://user-images.githubusercontent.com/97535534/184222389-2e686152-f074-448d-bd8a-39bb79393c2e.mp4

I don't understand where am I going wrong :(

**Comment by shine-jayakumar** [comment]
> ![image](https://user-images.githubusercontent.com/97535534/184224020-00b36011-e2fb-4b79-b32a-e2e4d5d3e95f.png)
> 
>  bandicam.2022-08-11.22-30-16-804.mp4 
> I don't understand where am I going wrong :(

I understand the issue. It's because of the different language it's not able to find the comment box either. I will make changes to the code.

**Comment by knmzz** [comment]
yes I see the comment box but it doesn't comment

**Comment by shine-jayakumar** [comment]
> yes I see the comment box but it doesn't comment
> 
> i changed the chrome language setting, but I couldn't change the chromedriver instagram language

I understand. I will update the code soon.

**Comment by knmzz** [comment]
Thank you,Okay. I am waiting to hear from you

**Comment by shine-jayakumar** [comment]
> Thank you,Okay. I am waiting to hear from you

Hi @knmzz, I have updated the code. Let me know if it's working for you.

**Comment by knmzz** [comment]
I don't understand why I can't run
goes to instagram opens the post but then just waiting

[*] => Script started
[*] => Loaded comments from follow.txt
[*] => Downloading webdriver for your version of Chrome
[*] => Initializing instagram user
[*] => Setting target to: #haiku
[*] => Attempting to log in with adesing007
[*] => Login successful
[*] => Skipping Save Login Info
[*] => Do not save login info: True
[*] => Opening target #haiku
[open_target]: Attempt - 1
[*] => No. of posts found: 2003434
[*] => Number of posts to like: 2003434
[*] => Checking if comments are disabled

**Comment by shine-jayakumar** [comment]
> I don't understand why I can't run goes to instagram opens the post but then just waiting
> 
> [_] => Script started [_] => Loaded comments from follow.txt [_] => Downloading webdriver for your version of Chrome [_] => Initializing instagram user [_] => Setting target to: #haiku [_] => Attempting to log in with adesing007 [_] => Login successful [_] => Skipping Save Login Info [_] => Do not save login info: True [_] => Opening target #haiku [open_target]: Attempt - 1 [_] => No. of posts found: 2003434 [_] => Number of posts to like: 2003434 [*] => Checking if comments are disabled

Hi @knmzz this isn't a bug. The script was supposed to wait for 30 seconds to check if comments are disabled. Since you pointed this out, I changed the code a bit. Now, for every post, the script will check if the comment is disabled or not. It wouldn't be waiting now.

**Comment by knmzz** [comment]
I waited for a long time but it didn't work
i don't understand what is the problem

[*] => Script started
[*] => Loaded comments from follow.txt
[*] => Downloading webdriver for your version of Chrome
[*] => Initializing instagram user
[*] => Setting target to: #haiku
[*] => Attempting to log in with adesing007
[*] => Login successful
[*] => Skipping Save Login Info
[*] => Do not save login info: True
[*] => Opening target #haiku
[open_target]: Attempt - 1
[*] => No. of posts found: 2004731
[*] => Number of posts to like: 2004731
[*] => Checking if comments are disabled
[*] => Comments are enabled
[*] => Liking post: 1
[like]: Attempt - 1
[*] => Commenting on the post
[comment]: Attempt - 1
[comment]: Attempt - 2

**Comment by shine-jayakumar** [comment]
> I waited for a long time but it didn't work i don't understand what is the problem
> 
> [_] => Script started [_] => Loaded comments from follow.txt [_] => Downloading webdriver for your version of Chrome [_] => Initializing instagram user [_] => Setting target to: #haiku [_] => Attempting to log in with adesing007 [_] => Login successful [_] => Skipping Save Login Info [_] => Do not save login info: True [_] => Opening target #haiku [open_target]: Attempt - 1 [_] => No. of posts found: 2004731 [_] => Number of posts to like: 2004731 [_] => Checking if comments are disabled [_] => Comments are enabled [_] => Liking post: 1 [like]: Attempt - 1 [_] => Commenting on the post [comment]: Attempt - 1 [comment]: Attempt - 2

You're using still using the previous version of the script. Clone the latest version and try again.

**Comment by knmzz** [comment]
![image](https://user-images.githubusercontent.com/97535534/185998312-9f373221-3097-436b-9a0a-df2d3f134be1.png)

![image](https://user-images.githubusercontent.com/97535534/185998669-a711543e-d4e8-4964-88c8-226c4b3664f6.png)
waiting like this nothing has changed :(

![image](https://user-images.githubusercontent.com/97535534/185998940-46066b3d-9832-46fa-b966-6e50c225e03d.png)

**Comment by shine-jayakumar** [comment]
> ![image](https://user-images.githubusercontent.com/97535534/185998312-9f373221-3097-436b-9a0a-df2d3f134be1.png)
> 
> ![image](https://user-images.githubusercontent.com/97535534/185998669-a711543e-d4e8-4964-88c8-226c4b3664f6.png) waiting like this nothing has changed :(
> 
> ![image](https://user-images.githubusercontent.com/97535534/185998940-46066b3d-9832-46fa-b966-6e50c225e03d.png)

Hi there,
I've made further changes. Clone again and let me know.
